### ISSUE TITLE
update docker build to latest version/automate builds

### ISSUE THREAD

**Issue by D-Nice** [commitsar-app/commitsar#92]
Just tried this tool, and ran into the issue where merge commits are being identified as non-compliant, but it seems this was fixed a few days ago. Since I'm using docker, would be useful to have that build updated, or better yet so it's automated :).

**Comment by fallion** [comment]
@D-Nice this should be released now.

**Comment by fallion** [comment]
If you're still running into problems let me know.

**Comment by fallion** [comment]
I checked out the failing pipeline you had. Some weird voodoo going on. 

According to Dockerhub latest should be up to date https://cloud.docker.com/u/commitsar/repository/docker/commitsar/commitsar

Can you try pinning 0.6.3 or using the Github action?

**Comment by fallion** [comment]
Actually upon further investigation I found that the commit in question is failing the regex for merge commit identification. https://github.com/D-Nice/solinfra-homepage/commit/8aee97aea260e9c61a9c129e90ae8ab0e960f547

I will fix it tomorrow and publish a new version.
