### ISSUE TITLE
commitsar does not need to be in the same folder as the repository

### ISSUE THREAD

**Issue by D-Nice** [commitsar-app/commitsar#93]
From my testing, of at least the latest current container (digest 195395165b624550f4d9100407b6d1207369cc843c74d0eb7b6d7a7d2c089a0c) the bolded statement in the readme doesn't hold true, which is a good thing. I believe just the current dir needs to be the repository you wish commitsar to test.

I run it in the following configuration:

`$ docker run -v "$PWD":/wd -w /wd --rm --entrypoint /app/commitsar fallion/commitsar`

from the repository I want tested.

I was also going to recommend changing the entrypoint from `./commitsar` which is why I need the entrypoint override, but I see that has been done already.

**Comment by fallion** [comment]
@D-Nice Sorry I overlooked this. I look into it.
